const {fs,root,path,read,json,escape:e,url,write,validate,promptFor} = require('./common.cjs');
const catalogue = validate(json('catalogue.json'));
const check = process.argv.includes('--check');
let stale = false;
function output(file, content) {
  if (fs.existsSync(path.join(root,file)) && read(file) === content) return;
  if (check) {console.error('Stale generated file: '+file);stale=true;} else write(file,content);
}
function head(title,prefix='',canonical='') {
  return `<!doctype html>\n<html lang="en" class="no-js"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#05080d"><title>${e(title)} | PatterTech</title><meta name="description" content="Explore original AI model outputs. Ten Cosmic Gravity simulations, their prompts and the details behind each run."><meta property="og:title" content="${e(title)} | PatterTech"><meta property="og:description" content="Open the demos. Compare the decisions. Read the original prompt."><meta property="og:type" content="website"><meta property="og:url" content="${catalogue.siteUrl+canonical}"><meta property="og:image" content="${catalogue.siteUrl}assets/pattertech-model-tests-card.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="PatterTech Model Tests: a real Cosmic Gravity simulation, with ten outputs from Astra and Sol."><meta name="twitter:card" content="summary_large_image"><link rel="canonical" href="${catalogue.siteUrl+canonical}"><link rel="icon" href="${prefix}assets/pattertech-mark.svg"><link rel="preload" href="${prefix}assets/fonts/spacegrotesk.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="${prefix}assets/site.css"><script src="${prefix}assets/catalogue.js" defer></script><script src="${prefix}assets/site.js" defer></script></head><body data-prefix="${prefix}"><a class="skip" href="#main">Skip to content</a><header class="header wrap"><a class="brand" href="${prefix || './'}" aria-label="PatterTech Model Tests home"><img src="${prefix}assets/pattertech-mark.svg" alt="" width="34" height="34"><span><b>Patter</b>Tech</span></a><nav class="nav" aria-label="Main"><a href="${prefix || './'}#results">Compare</a><a class="desktop-link" href="${prefix}experiments/cosmic-gravity/#method">How we test</a><a href="${catalogue.repositoryUrl}">GitHub ↗</a></nav></header>`;
}
function footer(prefix='') {return `<footer class="footer wrap"><p>A PatterTech project. Made to be explored.</p><div class="actions"><a href="${prefix}experiments/cosmic-gravity/#method">Methodology</a><a href="${catalogue.repositoryUrl}/blob/main/LICENSE">MIT licence</a><a href="${catalogue.repositoryUrl}">Source ↗</a></div></footer><div class="sr-only" id="announcement" role="status" aria-live="polite"></div></body></html>\n`;}
function viewer() {return `<dialog class="viewer" id="viewer" aria-labelledby="viewer-title"><div class="viewer-inner"><div class="viewer-toolbar"><h2 id="viewer-title">Cosmic Gravity</h2><div class="viewer-switch" role="group" aria-label="Switch model"><button data-switch="Astra">Astra</button><button data-switch="Sol">Sol</button></div><div class="actions"><a id="viewer-original" class="button" target="_blank" rel="noopener">Open original ↗</a><button id="viewer-restart">Restart</button><button class="viewer-close" id="viewer-close" autofocus>Close</button></div></div><p class="viewer-note">Original output. Switching models or closing this viewer restarts the simulation. Use Tab to reach the host controls.</p><div class="frame-slot" id="frame-slot"></div><button id="viewer-exit" class="viewer-exit">Return to results</button></div></dialog><dialog class="viewer source-dialog" id="source-dialog" aria-labelledby="source-title"><div class="viewer-toolbar"><h2 id="source-title">Original HTML source</h2><button id="source-close" autofocus>Close</button></div><pre class="source-copy" id="source-content"></pre></dialog>`;}
const experiment=catalogue.experiments.find(x=>x.id==='cosmic-gravity');
const runs=experiment.runs, featured=runs.find(r=>r.id===experiment.featured);
const counts={runs:catalogue.experiments.reduce((n,x)=>n+x.runs.length,0),published:runs.filter(r=>r.publication==='published').length};
const efforts=['Light','Medium','High','Extra High','Ultra'];
function card(run,prefix='../../') {const promptLink=prefix?'#prompt':'experiments/cosmic-gravity/?run='+run.id+'#prompt';return `<article class="run-card" id="${run.id}"><a class="poster-link" href="${prefix}${url(run.path)}" data-play="${run.id}" aria-label="Play ${e(run.model+' '+run.effort)}"><img src="${prefix}${run.poster}" alt="Original ${e(run.model+' '+run.effort)} Cosmic Gravity scene and controls" width="960" height="540" loading="${prefix&&run.effort==='Ultra'?'eager':'lazy'}"><span class="play-badge">Play simulation ↗</span></a><div class="run-heading"><h3>${e(run.model)} <span style="color:var(--muted)">${e(run.effort)}</span></h3>${run.id===experiment.featured?'<span class="tag">Featured</span>':''}</div><div class="run-links"><a href="${prefix}${url(run.path)}" target="_blank" rel="noopener">Open original ↗</a><a href="${prefix}${url(run.path)}" download>Download</a><a href="${prefix}${url(run.path)}" data-source="${run.id}" class="js-only">View source</a><a href="${promptLink}" ${prefix?`data-prompt-run="${run.id}"`:""}>Prompt</a></div></article>`;}
function resultBrowser(prefix) {return `<div class="selector-bar"><nav class="efforts" aria-label="Effort level">${efforts.map(v=>`<a href="#effort-${v.toLowerCase().replaceAll(' ','-')}" data-effort="${v}" aria-current="${v==='Ultra'}">${v}</a>`).join('')}</nav><p class="selector-note">One live demo at a time. Compare by switching.</p></div><p id="selection-error" class="notice" hidden></p>${efforts.map(v=>`<section class="pair" data-pair="${v}" id="effort-${v.toLowerCase().replaceAll(' ','-')}" aria-label="${v} outputs">${runs.filter(r=>r.effort===v).map(r=>card(r,prefix)).join('')}</section>`).join('')}<details class="all-results"><summary>All ten original files</summary><div class="run-list">${runs.map(r=>`<a href="${prefix}${url(r.path)}">${e(r.model+' / '+r.effort)} <span>Open ↗</span></a>`).join('')}</div></details><p class="run-note">Screenshots show real default scenes. The simulations use randomness, so each launch will look different.</p>`;}
const home = `${head('Model Tests')}
<main id="main" class="wrap" data-experiment="cosmic-gravity"><section class="hero" aria-labelledby="home-title"><div class="hero-heading"><div><div class="eyebrow">PatterTech / Model Tests</div><h1 id="home-title">Same brief.<br>Different universes.</h1></div><p>What changes when you give the same task to different models? Open the results and see for yourself.</p></div><div class="feature home-feature"><img src="${featured.poster}" srcset="${featured.poster} 960w, assets/previews/astra-ultra-hero.webp 1920w" sizes="(max-width: 800px) calc(100vw - 48px), (max-width: 1336px) calc(100vw - 96px), 1240px" width="960" height="540" alt="Astra Ultra's luminous spiral galaxies and gravity controls" fetchpriority="high"><video id="ambient-preview" muted loop playsinline preload="none" aria-hidden="true" data-src="assets/previews/astra-ultra-preview.mp4" data-mobile-src="assets/previews/astra-ultra-preview-mobile.mp4"></video><div class="shade"></div><div class="feature-caption"><div><span class="eyebrow">Experiment 01</span><h2>Cosmic Gravity</h2><p>Ten original simulations. Two models. Five effort levels.</p></div><div class="actions"><a class="button primary" href="${url(featured.path)}" data-play="astra-ultra">Play Astra Ultra <span aria-hidden="true">↗</span></a><a class="button secondary" href="#results">Explore all ${runs.length} <span aria-hidden="true">→</span></a></div></div></div><div class="feature-meta"><span>Astra Ultra is featured here. This is an editorial choice, not a ranking.</span><button id="preview-toggle" class="js-only" aria-pressed="false">Play preview</button></div></section>
<section class="section" id="results" aria-labelledby="results-title"><div class="section-head"><div><div class="eyebrow">Cosmic Gravity</div><h2 id="results-title">Explore all ${runs.length}</h2></div><p>Choose an effort level, compare the scenes, then open either model's original simulation.</p></div>${resultBrowser('')}</section>
<section class="section editorial" id="prompt"><div><div class="eyebrow">Behind the results</div><h2>The prompt is part<br>of the experiment.</h2><a class="text-link" href="experiments/cosmic-gravity/#prompt">Read the full prompt →</a></div><div><p>The brief asks for a self-contained HTML gravity simulation. No libraries, no external assets, and plenty of room for the model to make its own decisions.</p><p>These are practical examples, not a formal benchmark. Historical runs used different working contexts, and the earliest four predate the naming paragraph.</p><a class="text-link" href="experiments/cosmic-gravity/#method">Understand the comparison →</a></div></section></main>${viewer()}${footer()}`;
output('index.html',home);
output('experiments/cosmic-gravity/index.html',`${head('Cosmic Gravity: prompt and methodology','../../','experiments/cosmic-gravity/').replace('<body data-prefix=', '<body data-page="context" data-prefix=')}
<main id="main" class="wrap" data-experiment="cosmic-gravity"><div class="breadcrumb"><a href="../../">Model Tests</a> / Experiment 01</div><div class="experiment-intro"><div><div class="eyebrow">Cosmic Gravity</div><h1>Prompt &amp; methodology</h1></div><p>Read the brief, check the historical context and prepare a new run.</p></div><a class="button secondary" id="results" href="../../#results">← Compare all ten results</a>
<section class="section editorial" id="method"><div><div class="eyebrow">How to read this</div><h2>Compare the decisions.<br>Keep the context.</h2></div><div><p>Both models received the same simulation brief. Effort labels identify the requested setting; they do not establish a score or a guaranteed improvement.</p><p>These are historical agent runs. Tool access, working context and interventions were not fully recorded. The first four used the original brief; later runs added the same short naming paragraph with a different model label.</p><p>We preserve the delivered HTML. Site improvements and recordings are made separately. Astra Ultra is featured for exploration, not as a measured winner.</p><a class="text-link" href="${catalogue.repositoryUrl}/blob/main/docs/methodology.md">Methodology and future run protocol →</a><br><a class="text-link" href="${catalogue.repositoryUrl}/blob/main/docs/validation.md">Validation evidence and limitations →</a></div></section>
<section class="section" id="prompt"><div class="section-head"><div><div class="eyebrow">The original brief</div><h2>Read it. Reuse it.</h2></div><p>Choose a result to see the prompt variant it used. A new run adds the agreed naming paragraph, even for Light and Medium.</p></div><div class="prompt-toolbar js-only"><label for="prompt-run">Result</label><select id="prompt-run">${runs.map(r=>`<option value="${r.id}" ${r.id===featured.id?'selected':''}>${e(r.model+' / '+r.effort)}</option>`).join('')}</select><label for="prompt-mode">Version</label><select id="prompt-mode"><option value="historical">Used for this result</option><option value="new">Prepare a new run</option></select><button id="copy-prompt">Copy prompt</button><span id="copy-status" role="status"></span></div><p class="notice" id="prompt-context">Astra Ultra used the original brief plus the naming paragraph.</p><details id="prompt-details" open><summary>Full prompt</summary><pre class="prompt-copy" id="prompt-text">${e(promptFor(experiment,featured))}</pre></details><a class="text-link" href="../../${url(experiment.prompt)}">Open canonical prompt file →</a></section></main>${viewer()}${footer('../../')}`);
output('assets/catalogue.js',`/* Generated by tools/generate.cjs. Do not edit. */\nwindow.MODEL_TESTS = ${JSON.stringify({experiments:catalogue.experiments.map(x=>({...x,promptTemplates:{original:promptFor(x,{...x.runs[0],promptVariant:'original'}),named:promptFor(x,x.runs[0],false),label:x.runs[0].model+'-'+x.runs[0].effort}}))})};\n`);
const listing = `| Model | Effort | Original HTML | Publication |\n| --- | --- | --- | --- |\n${runs.map(r=>`| ${r.model} | ${r.effort} | [Open](${url(r.path)}) | ${r.publication==='published'?'Published':'Prepared locally'} |`).join('\n')}`;
for(const [file,relative] of [['README.md',false],['HTML - Space/README.md',true]]) {
  if(!fs.existsSync(path.join(root,file))) continue;
  const start='<!-- RESULTS:START -->',end='<!-- RESULTS:END -->';
  const text=read(file);if(!text.includes(start)) continue;
  const table=relative ? listing.replaceAll('HTML%20-%20Space/','') : listing;
  const segment=`${start}\n\n${table}\n\n${end}`;
  output(file,text.slice(0,text.indexOf(start))+segment+text.slice(text.indexOf(end)+end.length));
}
if(stale) process.exitCode=1;else console.log(check?'Catalogue, original hashes and generated content verified.':'Static site and catalogue views generated.');
